---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-101-role
subjects:
  - kind: ServiceAccount
    name: k8s-101-role
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-101-role
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gitops-agent
  namespace: default
spec:
  schedule: "*/3 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: k8s-101-role
          containers:
            - name: main
              image: poor-mans-gitops:v1
              imagePullPolicy: IfNotPresent
              args:
                - /bin/sh
                - -c
                - git clone https://github.com/gitops-workshop/poor-mans-gitops && cat poor-mans-gitops/apps/hello-world.yaml | envsubst | kubectl apply -l apps.kubernetes.io/instance=hello-world --prune --validate=false -f -
          restartPolicy: Never
